#pragma once

#ifndef ERROR_CODES_H
    #define ERROR_CODES_H

    enum exit_status{
        NO_ERROR,
        
        FAILED_TO_INITIALIZE_GLFW,
        FAILED_TO_CREATE_WINDOW,
        FAILED_TO_CREATE_MOUSE_CALLBACK,
        FAILED_TO_INITIALIZE_GLEW,
        FAILED_TO_CREATE_USER_INPUT_HANDLER,
        FAILED_TO_CREATE_AUDIO_PLAYBACK,
        FAILED_TO_INITIALIZE_AUDIO_PLAYBACK,
        FAILED_TO_CREATE_RENDERER,
        FAILED_TO_CREATE_TEXT_RENDERER,
        FAILED_TO_CREATE_BACKGROUND_RENDERER,
        FAILED_TO_CREATE_SCENE,
        FAILED_TO_INITIALIZE_SCENE,
        FAILED_TO_CREATE_APPLICATION_CONTENT,
        FAILED_TO_INITIALIZE_APPLICATION_CONTENT,

        //NOTE: partial failure reasons
        FAILED_TO_READ_INPUT_FILE            = 32,
        FAILED_TO_CREATE_PROGRAMS            = 64,
        FAILED_TO_LOAD_TEXTURE               = 128,
        FAILED_TO_INITIALIZE_FONT_LIBRARY    = 256,
        FAILED_TO_CREATE_FONT_FACE           = 512,
        FAILED_TO_OPEN_AUDIO_DEVICE          = 1024,
        FAILED_TO_CREATE_AUDIO_CONTEXT       = 2048,
        FAILED_TO_GET_AUDIO_DEVICE_SPECIFIER = 4096,
        FAILED_TO_SET_AUDIO_SOURCE_CONFIG    = 8192,
        FAILED_TO_SET_AUDIO_LISTENER_CONFIG  = 16384,
        FAILED_TO_CREATE_AUDIO_DEVICE        = 32768,
        FAILED_TO_CREATE_AUDIO_SOURCE        = 65536,
        FAILED_TO_CREATE_AUDIO_LISTENER      = 131072,
        FAILED_TO_ADD_BACKGROUND_SOUND       = 262144,

        //WINDOW_IS_NOT_INITIALIZED
    };

#endif /* ERROR_CODES_H */
